<?php

namespace zinux\kernel\exceptions;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-08 at 07:22:45.
 */
class appExceptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var appException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new appException("ErRor");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers zinux\kernel\exceptions\appException::SendErrorCode
     * @todo   Implement testSendErrorCode().
     */
    public function testSendErrorCode()
    {
        $this->object->SendErrorCode(300);
    }

    /**
     * @covers zinux\kernel\exceptions\appException::GetErrorCode
     * @todo   Implement testGetErrorCode().
     */
    public function testGetErrorCode()
    {
        $this->object->SendErrorCode(100);
        $this->assertEquals(100, $this->object->GetErrorCode());
    }

    /**
     * @covers zinux\kernel\exceptions\appException::GetErrorTraceAsString
     * @todo   Implement testGetErrorTraceAsString().
     */
    public function testGetErrorTraceAsString()
    {
        $this->assertTrue(true);
    }

}
